---
markdown: kramdown
highlighter: rouge
title: Hydeout
tagline: A Jekyll theme
description: The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme
  for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.
url: https://example.com
baseurl: ''
author:
  name: Andrew Fong
  url: https://twitter.com/fongandrewc
paginate: 10
exclude:
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: true
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
